In [3]:
import numpy as np

In [129]:
# 1
datas = [[40, 20, 75, 42, 11],
       [30, 39, 92, 21, 45],
       [94, 40, 15, 27, 82]]
arr=np.array(datas)
arr

array([[40, 20, 75, 42, 11],
       [30, 39, 92, 21, 45],
       [94, 40, 15, 27, 82]])

In [131]:
arr[:,-1]

array([11, 45, 82])

In [16]:
# 2
# numpy함수를 이용하여 10이하의 짝수와 홀수 각각의 리스트를 생성하고,
# 이 두가지 리스트를 사용하여 2차원의 데이터를 만들어라.
# 출력 결과: 
# array([[ 1,  3,  5,  7,  9],
#        [ 2,  4,  6,  8, 10]])

In [32]:
a1d = np.arange(1,11,2)
a2d = np.arange(2,11,2)

In [35]:
arr=np.array([a1d, a2d])
arr

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [36]:
# 3
# 10부터 30까지 정수로 이루어진 1차원배열을 만든다음 2차원  (7, -1) 형태로 변환하시오.

# 그리고 최댓값과 최솟값을 구하시오.

In [43]:
x=np.arange(10,31,1)
print(x.max())
print(x.min())

30
10


In [138]:
# 문제: 아래 배열을 3행 4열 형태로 reshape 하시오. 변환된 배열에서 마지막 행만 출력하시오
datas = [[10, 20, 30, 40, 50, 60],
         [70, 80, 90, 100, 110, 120]]

np.datas.reshape(3,4)

AttributeError: module 'numpy' has no attribute 'datas'

In [44]:
# # 4
# 코드와 그  출력값이 다음과 같을 때 0.6664104711248381을 출력하는 코드를 작성하시오

In [4]:
np.random.seed(12)
print(np.random.random())
print(np.random.random())
print(np.random.random())
print(np.random.random())

0.15416284237967237
0.7400496965154048
0.26331501518513467
0.5337393933802977


In [134]:
# 5
# seed값을 5로 고정한 후 random.randint(1,11)을 세번 실행했을 때 나오는 값을 구하시오.

np.random.seed(5)
np.random.randint(1,11)
np.random.randint(1,11)
np.random.randint(1,11)

7

In [84]:
# 6
# (1) 1~25까지 step이 3개인 1차원의 배열을 만들고,
# (2) reshape을 이용하여 3x3행렬로 만드시오.

(1)
arr=np.arange(1,26,3)
arr

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25])

In [86]:
(2)
a2d=arr.reshape(3,3)
a2d

array([[ 1,  4,  7],
       [10, 13, 16],
       [19, 22, 25]])

In [144]:
# 7
# arr의 각 행에서 최댓값만 추출하여 1차원 배열 형태로 출력하시오.

np.random.seed(11)
arr=np.random.random((4,5))
print(arr.max(axis=1))

[0.72493393 0.94180665 0.89390417 0.63233401]


In [104]:
# 8
# np.random.randint(1, 45, (3,4))를 출력하고 리스트 형태로 변환하여 출력하시오.
# ----------------
# 결과값 예시: [[2, 27, 6, 41], [27, 23, 3, 3], [34, 30, 43, 25]]

list(np.random.randint(1,45,(3,4)))

[array([ 4, 36, 18,  7], dtype=int32),
 array([41,  2, 40, 37], dtype=int32),
 array([ 9,  6, 38, 28], dtype=int32)]

In [105]:
# 9
# reshape 함수를 사용해 1부터 30까지의 숫자 중 짝수를 찾아 (3,5)의 행렬로 만드시오.

b=np.arange(2,31,2)
b.reshape(3,5)

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [128]:
# 10
#range을 이용하여 1~20까지 숫자를 나열한 후 4행 5형로 정렬하고 그 중 각 행의 최소값을 추출하시오

c=np.arange(1,21,1)
d=c.reshape(4,5)


array([ 1,  6, 11, 16])