# numpy 생성

In [1]:
import numpy as np

In [2]:
np.__version__

'2.2.6'

# numpy 객체 생성

In [9]:
a = [1, 2, 3, 4, 5]
arr = np.array(a)
arr

array([1, 2, 3, 4, 5])

In [7]:
type(arr)

numpy.ndarray

In [10]:
len(arr)

5

In [12]:
# 튜플 -> ndarray
a = (1, 2, 3, 4, 5)
arr = np.array(a)
arr

array([1, 2, 3, 4, 5])

In [13]:
arr.size

5

In [14]:
arr.dtype

dtype('int64')

In [15]:
a = ['a', 2, 3, 4, 5]
arr = np.array(a)
arr

array(['a', '2', '3', '4', '5'], dtype='<U21')

In [16]:
a = [1.1, 2, 3, 4, 5]
arr = np.array(a)
arr

array([1.1, 2. , 3. , 4. , 5. ])

# 2차원 데이터 만들기

In [27]:
a2d = [[1, 2, 3], [3, 4, 5], [7, 8, 9]]
a2d

[[1, 2, 3], [3, 4, 5], [7, 8, 9]]

In [29]:
a2d = np.array(a2d)
a2d

array([[1, 2, 3],
       [3, 4, 5],
       [7, 8, 9]])

In [30]:
len(a2d)

3

In [31]:
# array의 전체 요소의 갯수
a2d.size

9

In [33]:
a2d.shape

(3, 3)

# numpy 객체 저장 및 로딩

In [34]:
a2d

array([[1, 2, 3],
       [3, 4, 5],
       [7, 8, 9]])

In [35]:
np.save('my_array', a2d)

In [36]:
a2d = np.load('my_array.npy')
a2d

array([[1, 2, 3],
       [3, 4, 5],
       [7, 8, 9]])

# numpy 내장함수

In [37]:
np.zeros(4)

array([0., 0., 0., 0.])

In [38]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [39]:
# 1차원
np.ones((7,))

array([1., 1., 1., 1., 1., 1., 1.])

In [40]:
# 2차원
np.ones((4,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [41]:
np.full((7,),5)

array([5, 5, 5, 5, 5, 5, 5])

In [43]:
np.full((7,2),5)

array([[5, 5],
       [5, 5],
       [5, 5],
       [5, 5],
       [5, 5],
       [5, 5],
       [5, 5]])

In [44]:
np.full((4,2,3),5)

array([[[5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5]]])

In [45]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [47]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
np.arange(5, 30+1)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30])

In [49]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [50]:
np.linspace(0,20,15)

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        , 11.42857143, 12.85714286,
       14.28571429, 15.71428571, 17.14285714, 18.57142857, 20.        ])

In [52]:
arr = np.arange(1, 21+1)

In [54]:
a2d = arr.reshape(3,7)
a2d

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21]])

In [55]:
a2d.shape

(3, 7)

In [56]:
a2d = arr.reshape(7,3)
a2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [57]:
a2d.shape

(7, 3)

In [58]:
a1d = a2d.reshape(21)
a1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21])

In [60]:
a2d = a1d.reshape(-1,3)
a2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [61]:
a2d.max()

np.int64(21)

In [62]:
a2d.min()

np.int64(1)

In [63]:
a2d.sum()

np.int64(231)

In [64]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21])

In [65]:
arr.sum()

np.int64(231)

In [66]:
arr.mean()

np.float64(11.0)

In [67]:
print(arr.std())

6.0553007081949835


In [68]:
arr.var()

np.float64(36.666666666666664)

In [71]:
a = np.arange(5,20)
a.size

15

In [72]:
a.reshape(3, 5)

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [73]:
np.arange(5,20).reshape(3,5)

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [74]:
import random

In [75]:
random.random()

0.2478701963247245

In [76]:
np.random.random(5)

array([0.65376595, 0.1511302 , 0.93564236, 0.70481645, 0.33957247])

In [77]:
np.random.random((5,))

array([0.57682663, 0.27324851, 0.67460874, 0.98630001, 0.37979578])

- 랜덤 seed

In [78]:
# 0~~1 사이의 실수로 난수 발생

In [79]:
np.random.random((3,5))

array([[0.29522742, 0.17259616, 0.66728931, 0.11447558, 0.01241698],
       [0.0281502 , 0.19986159, 0.91311779, 0.40945496, 0.84155346],
       [0.89901676, 0.00552809, 0.51075632, 0.23675898, 0.54513949]])

In [80]:
random.seed(4)
random.random()

0.23604808973743452

In [81]:
# random.seed(3)
# 랜덤을 뽑는 숫자가 나오는 패턴을 일치시키는 방법
# 첫번째 실행에 나온 숫자, 두번째 실행에 나온 숫자,... => 패턴
# 하나의 셀에만 적용

In [82]:
random.random()

0.1031660342307158

In [111]:
np.random.seed(3)

In [112]:
np.random.random((3,5))

array([[0.5507979 , 0.70814782, 0.29090474, 0.51082761, 0.89294695],
       [0.89629309, 0.12558531, 0.20724288, 0.0514672 , 0.44080984],
       [0.02987621, 0.45683322, 0.64914405, 0.27848728, 0.6762549 ]])

In [109]:
np.random.random((3,5))

array([[0.86053391, 0.5862529 , 0.28348786, 0.27797751, 0.45462208],
       [0.20541034, 0.20137871, 0.51403506, 0.08722937, 0.48358553],
       [0.36217621, 0.70768662, 0.74674622, 0.69109292, 0.68918041]])

In [87]:
np.random.seed(9)

In [89]:
np.random.randint(1, 45, (7,))

array([29, 23,  2, 23, 41, 28, 34], dtype=int32)

In [93]:
np.random.randint(1, 100, (3, 4))

array([[29, 55,  1, 65],
       [19, 64, 38, 57],
       [57, 72, 38, 47]], dtype=int32)

In [97]:
X= np.random.randint(1, 100, (3,4))

In [98]:
X.max()

np.int32(97)

In [99]:
X.min()

np.int32(3)

In [100]:
X.std()

np.float64(27.514011581980068)

In [101]:
X.var()

np.float64(757.0208333333334)

In [102]:
a = np.array([3,4,5,6,7,8,9,10])
sorted(a.tolist())

[3, 4, 5, 6, 7, 8, 9, 10]

In [103]:
type(a)

numpy.ndarray

In [104]:
np.median(a)

np.float64(6.5)

In [115]:
np.random.seed(3)
X = np.random.randint(1, 100, (4,5))
X

array([[25,  4, 57, 73,  1],
       [22, 20, 75, 42, 11],
       [22, 39, 97, 21, 45],
       [94, 40, 15, 27, 82]], dtype=int32)

In [116]:
X.max(axis=0)

array([94, 40, 97, 73, 82], dtype=int32)

In [117]:
X

array([[25,  4, 57, 73,  1],
       [22, 20, 75, 42, 11],
       [22, 39, 97, 21, 45],
       [94, 40, 15, 27, 82]], dtype=int32)

In [118]:
X>70

array([[False, False, False,  True, False],
       [False, False,  True, False, False],
       [False, False,  True, False, False],
       [ True, False, False, False,  True]])

In [119]:
(X>70).sum()

np.int64(5)

In [121]:
X[X>70]

array([73, 75, 97, 94, 82], dtype=int32)

In [122]:
X[X>70].size

5

## 실습

In [123]:
import numpy as np

In [126]:
X = np.arange(2, 33, 2).reshape(4,4)
X

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [127]:
X

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [128]:
X.shape

(4, 4)

In [129]:
X.size

16

In [130]:
X.dtype

dtype('int64')

In [131]:
X.max()

np.int64(32)

In [132]:
X.min()

np.int64(2)

In [133]:
X

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [135]:
np.random.seed(3)
X=np.random.randint(1,100,(4,5))
X

array([[25,  4, 57, 73,  1],
       [22, 20, 75, 42, 11],
       [22, 39, 97, 21, 45],
       [94, 40, 15, 27, 82]], dtype=int32)

In [136]:
X.max(axis=0)

array([94, 40, 97, 73, 82], dtype=int32)

In [137]:
X.argmax()

np.int64(12)

In [138]:
X.argmin()

np.int64(4)

In [140]:
X

array([[25,  4, 57, 73,  1],
       [22, 20, 75, 42, 11],
       [22, 39, 97, 21, 45],
       [94, 40, 15, 27, 82]], dtype=int32)

In [141]:
X.argmax(axis=1)

array([3, 2, 2, 0])

In [143]:
x=np.random.randint(1,100,7)
x

array([52, 91, 70, 98, 30, 25, 63], dtype=int32)

In [144]:
x[2]

np.int32(70)

In [145]:
x[-1]

np.int32(63)

In [147]:
X

array([[25,  4, 57, 73,  1],
       [22, 20, 75, 42, 11],
       [22, 39, 97, 21, 45],
       [94, 40, 15, 27, 82]], dtype=int32)

In [148]:
X[1][2]

np.int32(75)

In [149]:
X[1,2]

np.int32(75)

In [150]:
X[3,4]

np.int32(82)

In [151]:
X

array([[25,  4, 57, 73,  1],
       [22, 20, 75, 42, 11],
       [22, 39, 97, 21, 45],
       [94, 40, 15, 27, 82]], dtype=int32)

In [152]:
X[0,:3]

array([25,  4, 57], dtype=int32)

In [153]:
X[2:,:3]

array([[22, 39, 97],
       [94, 40, 15]], dtype=int32)

In [154]:
X

array([[25,  4, 57, 73,  1],
       [22, 20, 75, 42, 11],
       [22, 39, 97, 21, 45],
       [94, 40, 15, 27, 82]], dtype=int32)

In [155]:
X[1:4,1:3]

array([[20, 75],
       [39, 97],
       [40, 15]], dtype=int32)

In [156]:
X[:2,2:]

array([[57, 73,  1],
       [75, 42, 11]], dtype=int32)

In [159]:
X=np.arange(1,26).reshape(-1,5)
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [161]:
Y=X[X%2==1]
Y

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25])

In [164]:
x

array([52, 91, 70, 98, 30, 25, 63], dtype=int32)

In [165]:
score_list = [77, 46, 55, 99, 87, 81]
score_list

[77, 46, 55, 99, 87, 81]

In [166]:
new_score_list=[]
for score in score_list:
    new_score_list.append(score-7)
new_score_list

[70, 39, 48, 92, 80, 74]

In [167]:
np.array(score_list)-7

array([70, 39, 48, 92, 80, 74])

In [168]:
x

array([52, 91, 70, 98, 30, 25, 63], dtype=int32)

In [169]:
x-10

array([42, 81, 60, 88, 20, 15, 53], dtype=int32)

In [170]:
x//2

array([26, 45, 35, 49, 15, 12, 31], dtype=int32)

In [171]:
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [172]:
X*2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50]])

In [173]:
X+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [174]:
X//2

array([[ 0,  1,  1,  2,  2],
       [ 3,  3,  4,  4,  5],
       [ 5,  6,  6,  7,  7],
       [ 8,  8,  9,  9, 10],
       [10, 11, 11, 12, 12]])

In [175]:
x = [56, 75, 88, 92, 66]

In [177]:
np.array(x)-5

array([51, 70, 83, 87, 61])

In [197]:
np.random.seed(5)

In [200]:
np.random.randint(1,11)

7

In [194]:
np.random.seed(5)