# Neural Networks and Deep Learning

In [1]:
# import lib
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import os

In [2]:
data_path = 'datas_dnn/Churn_Modelling.csv'
df = pd.read_csv(data_path)

In [3]:
df.isna().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [4]:
df.head(4)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0

In [5]:
y = df['Exited']

In [6]:
X = df.loc[:,'CreditScore':'EstimatedSalary']

In [7]:
y.unique()

array([1, 0])

In [8]:
X.head(3)

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57

In [9]:
X['Geography'].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [10]:
X['Gender'].unique()

array(['Female', 'Male'], dtype=object)

In [11]:
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer

In [12]:
ct = ColumnTransformer([('onehot', OneHotEncoder(), [1]), ('label', OrdinalEncoder(), [2])], remainder='passthrough')

In [13]:
X_ct = ct.fit_transform(X)
X_ct[0,:]

array([1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       6.1900000e+02, 4.2000000e+01, 2.0000000e+00, 0.0000000e+00,
       1.0000000e+00, 1.0000000e+00, 1.0000000e+00, 1.0134888e+05])

In [14]:
X.head(3)

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57

In [15]:
X_ct

array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]], shape=(10000, 12))

In [16]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [17]:
X_ct

array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]], shape=(10000, 12))

In [18]:
sc = MinMaxScaler()

In [19]:
X_scaled = sc.fit_transform(X_ct)
X_scaled.shape

(10000, 12)

In [20]:
X_scaled[0,:]

array([1.        , 0.        , 0.        , 0.        , 0.538     ,
       0.32432432, 0.2       , 0.        , 0.        , 1.        ,
       1.        , 0.50673489])

In [21]:
X.head(1)

CreditScore Geography  Gender  Age  Tenure  Balance  NumOfProducts  \
0          619    France  Female   42       2      0.0              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
X_scaled.shape

(10000, 12)

In [24]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

In [25]:
# modeling

In [26]:
import tensorflow as tf
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense

In [27]:
X_train.shape

(8000, 12)

In [28]:
model = Sequential()

In [29]:
model.add(keras.Input(shape=(12,)))
model.add(Dense(units=6, activation='relu'))
model.add(Dense(units=8, activation='relu'))
model.add(Dense(units=1, activation='sigmoid'))
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 6)                   │              78 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 8)                   │              56 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 1)                   │               9 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 143 (572.00 B)

 Trainable params: 143 (572.00 B)

 Non-trainable params: 0 (0.00 B)

In [30]:
# compile

In [31]:
model.compile(optimizer='adam',
             loss='binary_crossentropy',
             metrics=['accuracy']
             )

In [32]:
model.fit(X_train, y_train, epochs=20, batch_size=10)

Epoch 1/20
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 625us/step - accuracy: 0.7945 - loss: 0.4942
Epoch 2/20
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 625us/step - accuracy: 0.7945 - loss: 0.4718
Epoch 3/20
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 661us/step - accuracy: 0.7947 - loss: 0.4614
Epoch 4/20
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 629us/step - accuracy: 0.8011 - loss: 0.4493
Epoch 5/20
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 632us/step - accuracy: 0.8089 - loss: 0.4403
Epoch 6/20
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 634us/step - accuracy: 0.8130 - loss: 0.4332
Epoch 7/20
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 640us/step - accuracy: 0.8163 - loss: 0.4284
Epoch 8/20
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 633us/step - accuracy: 0.8198 - loss: 0.4250
Epoch 9/20
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 638us/step - accuracy: 0.8219 - loss: 0.4225
Epoch 10/20
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 675us/step - accuracy: 0.8235 - loss: 0.4214
Epoch 11/20
800/800 ━━━━━━━━━━━━━━━━━━━━ 1s 662us/step - accuracy: 0.8224 - loss: 0.4197
Epoch 12/20
800/800 ━━━━━━━━━━

In [33]:
X_train.shape

(8000, 12)

In [34]:
model.evaluate(X_test, y_test)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 801us/step - accuracy: 0.8380 - loss: 0.3936


[0.39362820982933044, 0.8379999995231628]

# 다음 신규 데이터를 통해 분류
- Geography: France
- Credit Score: 600
- Gender: Male
- Age: 40
- Tenure: 3
- Balance: 60000
- Number of Products: 2
- Has Credit Card: Yes
- Is Active Member: Yes
- Estimated Salary: 50000

In [35]:
X.head(2)

CreditScore Geography  Gender  Age  Tenure   Balance  NumOfProducts  \
0          619    France  Female   42       2      0.00              1   
1          608     Spain  Female   41       1  83807.86              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58

In [36]:
new_data = [{'CreditScore':600, 'Geography':'France', 'Gender':'Male', 'Age':40, 'Tenure':3, 'Balance':60000, 'NumOfProducts':2, 'HasCrCard':1, 'IsActiveMember':1, 'EstimatedSalary':50000}]

In [37]:
df_new=pd.DataFrame(new_data)
df_new

CreditScore Geography Gender  Age  Tenure  Balance  NumOfProducts  \
0          600    France   Male   40       3    60000              2   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1            50000

In [38]:
new_data_ct = ct.transform(df_new)
new_data_ct

array([[1.e+00, 0.e+00, 0.e+00, 1.e+00, 6.e+02, 4.e+01, 3.e+00, 6.e+04,
        2.e+00, 1.e+00, 1.e+00, 5.e+04]])

In [39]:
new_data_sc = sc.transform(new_data_ct)
new_data_sc

array([[1.        , 0.        , 0.        , 1.        , 0.5       ,
        0.2972973 , 0.3       , 0.23914092, 0.33333333, 1.        ,
        1.        , 0.24996597]])

In [40]:
y_pred=model.predict(new_data_sc)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step


In [41]:
(y_pred>0.5).astype(int)

array([[0]])

In [42]:
import joblib

In [43]:
joblib.dump(ct, 'ct.pkl')

['ct.pkl']

In [44]:
joblib.dump(sc, 'sc.pkl')

['sc.pkl']

In [45]:
keras.models.save_model(model,'model.h5')

In [46]:
model.save('model.keras')

In [47]:
model2 = keras.models.load_model('model.h5')

In [48]:
keras.models.load_model('model.keras')

C:\Users\Admin\miniconda3\envs\tf_env\Lib\site-packages\keras\src\saving\saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 8 variables whereas the saved optimizer has 14 variables. 
  saveable.load_own_variables(weights_store.get(inner_path))


<Sequential name=sequential, built=True>

# 모델평가